#!/usr/bin/env python3

import sys
class App:
    def __init__(self, args):
        self.ext = args[1]
        self.count = int(args[2])
        self.main()

    def main(self):
        control = 1
        for x in range(0,self.count,1):
            f = open(self.createfname(control), 'w+')
            f.close()
            control += 1

    def createfname(self,num):
        return 'File_%s.%s' % (str(num),self.ext)


if __name__ == '__main__':
    App(sys.argv)