#!/usr/bin/env python2

import os, sys
import clipboard
###################################################################################
######## This script copies data from the clipboard and stores it in a file #######
###################################################################################

class App:
    def __init__(self, args):
        if len(args) > 2:
            print('args to long only one required!!!!!')
            return
        try:
            self.file = args[1]
        except IndexError:
            print('args required!!!!!')
            return

        if self.ifexists(self.file):
            print('File already exists!!!!!')
            return

        self.main()

    def ifexists(self, filename):
        fnames = os.listdir('.')
        boolean = False
        for x in fnames:
            if x == filename:
                boolean = True

        return boolean

    def main(self):
        data = clipboard.paste()
        f = open(self.file, 'w+')
        f.write(data)
        f.close()


args = sys.argv

if __name__ == '__main__':
    App(args)

